# Generated by Django 5.1.6 on 2025-02-10 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
    ]
